import type { NextPage } from 'next'
import Head from 'next/head'
import { Aims } from '../ui/sections/Aims'
import { PageFooter } from '../ui/sections/PageFooter'
import { PageHeader } from '../ui/sections/PageHeader'
import { Spec } from '../ui/sections/Spec'
import { Supporters } from '../ui/sections/Supporters'
import { Try } from '../ui/sections/Try'
import { What } from '../ui/sections/What'
import { Why } from '../ui/sections/Why'
import { YourSupport } from '../ui/sections/YourSupport'

const Home: NextPage = () => {
  return (

    <>
      <Head>
        <link rel="canonical" href="https://sim.com" />
        <meta charSet="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Status, Incident and Maintenance (SIM) Standard </title>

        <meta name="title" content="Status, Incident and Maintenance (SIM) Standard " />
        <meta name="description"
          content="A common standard for sharing health of Cloud services." />
        <meta name="robots" content="index, follow" />
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta name="language" content="English" />

        <meta name="color-scheme" content="light only" />
        <meta property="og:title" content="Status, Incident and Maintenance (SIM) Standard" />
        <meta property="og:site_name" content="SIM Standard" />
        <meta property="og:url" content="https://sim.com" />
        <meta property="og:description" content="A common standard for sharing health of Cloud services." />
        <meta property="og:image" content="/feature-3.png" />
        <meta name="twitter:card" content="summary" />
        <meta name="twitter:site" content="@mike_treestacks" />
        <meta name="twitter:creator" content="@mike_treestacks" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon.jpg" />
      </Head>
      <PageHeader />
      <section className="bg-white ">
        <div className="grid max-w-screen-xl px-4 pt-20 pb-8 mx-auto lg:gap-8 xl:gap-0 lg:py-16 lg:grid-cols-12 lg:pt-28">
          <div className="mr-auto place-self-center lg:col-span-7">
            <h1
              className="max-w-2xl mb-4 text-4xl font-extrabold leading-none tracking-tight md:text-5xl xl:text-6xl ">
              Status, Incident and <br />Maintenance (SIM) Standard.</h1>
            <p className="max-w-2xl mb-6 font-light text-gray-500 lg:mb-8 md:text-lg lg:text-xl ">
              Creating a standard for sharing the health of the internet by exposing the status of Cloud based
              services in a discoverable and machine readable manner.
            </p>
            <div className="space-y-4 sm:flex sm:space-y-0 sm:space-x-4">

            </div>
          </div>
          <div className="hidden lg:mt-0 lg:col-span-5 lg:flex">
            <img src="./hero1.png" alt="hero image" />
          </div>
        </div>
      </section>
      <section id="what" className="bg-gray-50 ">
        <div className="max-w-screen-xl px-4 py-8 mx-auto space-y-12 lg:space-y-20 lg:py-24 lg:px-6">
          <What />

        </div>
      </section>
      <section id="why" className="bg-gray-50 " >
        <div className="max-w-screen-xl px-4 py-8 mx-auto space-y-12 lg:space-y-20 lg:py-24 lg:px-6">
          <Why />
          <Aims />
        </div>
      </section>

      <section id="spec">
        <Spec />
      </section>

      <section id="try" className="">
        <div className="max-w-screen-xl px-4 py-8 mx-auto space-y-12 lg:space-y-20 lg:py-24 lg:px-6">
          <Try />
        </div>
      </section>
      <section className="bg-gray-50 " id="support">
        <div className="max-w-screen-xl px-4 py-8 mx-auto space-y-12 lg:space-y-20 lg:py-24 lg:px-6">
          <YourSupport />
        </div>
      </section>
      <section >
        <div className="max-w-screen-xl px-4 py-8 mx-auto space-y-12 lg:space-y-20 lg:py-24 lg:px-6">
          <Supporters />
        </div>
      </section>
      <PageFooter />
    </>


  )
}

export default Home
