import { Navbar } from 'flowbite-react'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Spec } from '../ui/sections/Spec'
import { What } from '../ui/sections/What'
import { Why } from '../ui/sections/Why'

const Home: NextPage = () => {
  return (

    <>
      <Head>
        <title>Status, Incidents and Maintenance (SIM) Standard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="grid max-w-screen-xl px-4  mx-auto ">

        <Navbar>

          <Navbar.Brand href="https://flowbite.com/">
            <img
              src="https://flowbite.com/docs/images/logo.svg"
              className="mr-3 h-6 sm:h-9"
              alt="Flowbite Logo"
            />
            <span className="self-center whitespace-nowrap text-xl font-semibold dark:text-white">
              Status, Incidents and Maintenance (SIM) Standard
            </span>
          </Navbar.Brand>
          <Navbar.Toggle />
          <Navbar.Collapse>
            <Navbar.Link
              href="#what"
              active={true}
            >
              What
            </Navbar.Link>
            <Navbar.Link href="#why">
              Why
            </Navbar.Link>
            <Navbar.Link href="#spec">
              The Spec
            </Navbar.Link>
          </Navbar.Collapse>
        </Navbar>
      </div>
      <section className="bg-white dark:bg-gray-900">
        <div className="grid max-w-screen-xl px-4 pt-20 pb-8 mx-auto lg:gap-8 xl:gap-0 lg:py-16 lg:grid-cols-12 lg:pt-28">
          <div className="mr-auto place-self-center lg:col-span-7">
            <h1
              className="max-w-2xl mb-4 text-4xl font-extrabold leading-none tracking-tight md:text-5xl xl:text-6xl dark:text-white">
              Status, Incidents and <br />Maintenance (SIM) Standard.</h1>
            <p className="max-w-2xl mb-6 font-light text-gray-500 lg:mb-8 md:text-lg lg:text-xl dark:text-gray-400">
              Creating a standard for sharing the health of the internet by exposing the status of Cloud based
              services in a discoverable and machine readable manner.
            </p>
            <div className="space-y-4 sm:flex sm:space-y-0 sm:space-x-4">

            </div>
          </div>
          <div className="hidden lg:mt-0 lg:col-span-5 lg:flex">
            <img src="./hero1.png" alt="hero image" />
          </div>
        </div>
      </section>
      <section className="bg-gray-50 dark:bg-gray-800">
        <div className="max-w-screen-xl px-4 py-8 mx-auto space-y-12 lg:space-y-20 lg:py-24 lg:px-6">
          <What />
          <Why />
        </div>
      </section>
      <Spec />

    </>


  )
}

export default Home
